### ISSUE TITLE
Графики

### ISSUE THREAD

**Issue by mackoel** [RSkooTy/bioprog#1]
Владислав, надо исправить:
- длинный вывод лучше грузить как лог, а не картинку в отчет,
- в отчете все графики должны быть подписаны: "Рисунок 1. Название", в тексте про каждый график должно быть упоминание и ссылка по номеру,
- в отчет должны быть номера страниц и оглавление,
- легенды на рисунках не должны закрывать линии,
- в легенде для последнего графика надо навести порядок, должно быть написано каким цветом какая компонента для какой точности, при этом глаз должен как-то выхватывать информацию иначе не зачем так строить, т.е. надо например каждую компоненту своим типом линии, каждую точность своим цветом,
- построение графика должно происходить по сохраненному в яайл выхлопу основного метода,
- код для функции правой части системы должен считывать из входного потока.

**Comment by RSkooTy** [comment]
Константин Николаевич, здравствуйте, отредактировал отчет. С уважением, Дубовицкий В.А.

**Comment by mackoel** [comment]
Владислав, изменений в коде не увидел. Когда посылаете исправление на проверку переставляйте меня в Assignee, справа сверху в интерфейсе
![image](https://github.com/RSkooTy/bioprog/assets/1510455/519b27aa-0fe0-4025-b618-3042b3e3c54a)

**Comment by mackoel** [comment]
Владислав, зачел.
